version: '3'

services:
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=product_database_user
      - POSTGRES_PASSWORD=compose-product_database_user
      - POSTGRES_DB=produtcs

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
